<?php
/**
 * Поле типа "Строка".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $field
 */

$field = $variables;
?>
<?= (isset($field['required']) ? '<div class="input_required">' : '') ?>

<input
	type="<?= $this->getFieldTypeAttribute($field) ?>"
	name="<?= $field['input_name'] ?>"
	placeholder="<?= $this->escape($field['title']) ?>"
	<?= (isset($field['required']) ? ' required ' : '') ?>
	value="<?= isset($field['value']) ? $this->escape($field['value']) : '' ?>"
	class="input order__input"
/>

<?= (isset($field['required']) ? '</div>' : '') ?>
