<?php
/**
 * Поле типа "Текст".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$field = $variables;
?>
<?= (isset($field['required']) ? '<div class="input_required">' : '') ?>
<textarea
	name="<?= $field['input_name'] ?>"
	placeholder="<?= $this->escape($field['title']) ?>"
	required class="input fancyboxPopup__textarea"
	<?= isset($field['required']) ? ' required ' : '' ?>
><?= isset($field['value']) ? $this->escape($field['value']) : '' ?></textarea>

<?= (isset($field['required']) ? '</div>' : '') ?>
