<?php
/**
 * Форма всплывающего окна "Заказать звонок".
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
?>

 <form enctype="multipart/form-data" class="fancyboxPopup__form">
	<input type="hidden" name="system_email_to" value="<?= $this->getCallbackAddressId($variables) ?>" />
	<h2 class="fancyboxPopup__head">Обратный звонок</h2>
	<div class="fancyboxPopup__inputsWrapper">
	<?php foreach ($variables['groups']['group'] as $group): ?>
		<?php foreach ($group['fields'] as $field): ?>
			<div class="<?= $this->getFormFieldClass($field) ?>">
				<?= $this->render($field, "data/form_field/{$field['type']}") ?>
			</div>
		<?php endforeach; ?>
	<?php endforeach; ?>
	</div>
	<input type="hidden" name="system_form_id" value="<?= $variables['form_id'] ?>" />
	<button type="submit" class="btn btn_color_white btn_bg_orange btn_order fancyboxPopup__btn">ЗАКАЗАТЬ ЗВОНОК</button>
</form>