	<!-- start: main-slider area -->
	<div class="main-slider">
		<div class="main-slider__wrapper swiper-container container">
			<ul class="main-slider__list swiper-wrapper">
				<li class="main-slider__item swiper-slide">
						<img src="public/img/slider-index-1.jpg" alt="slider" class="main-slider__img">
				</li>
				<li class="main-slider__item swiper-slide">
					<img src="public/img/slider-index-2.jpg" alt="slider" class="main-slider__img">
				</li>
				<li class="main-slider__item swiper-slide">
					<img src="public/img/slider-index-3.jpg" alt="slider" class="main-slider__img">
				</li>
			</ul>
			<a class="arrows arrows__left  swiper-button-prev" href="javascript: void(0)">
        <img class="arrows__icon svg" src="public/img/arrow-left-direction.svg" alt="arrow left">
      </a>
      <a class="arrows arrows__right swiper-button-next" href="javascript: void(0)">
        <img class="arrows__icon svg" src="public/img/right-black-arrow.svg" alt="arrow right">
      </a>
		</div>
	</div>
	<!-- end: main-slider area -->